### ISSUE TITLE
Highlighting in YAML syntax is screwed up

### ISSUE THREAD

**Issue by drybjed** [pearofducks/ansible-vim#1]
Infortunately the syntax highliting completely screwes up YAML-based Ansible syntax. This is how my files look now in terminal `vim` on Linux with `elflord` [colorscheme](https://vimcolorschemetest.googlecode.com/svn/colors/elflord.vim):

![2015-09-11-085956_1920x1080_scrot](https://cloud.githubusercontent.com/assets/1043958/9808945/4b30b27e-5864-11e5-9101-1ecc9d4db9b9.png)

This is the same code in GTK `gvim`, using `solarized` [colorscheme](https://github.com/altercation/vim-colors-solarized):
![2015-09-11-090939_1920x1080_scrot](https://cloud.githubusercontent.com/assets/1043958/9809034/03c0ae70-5865-11e5-8c41-9ccfffd10b4d.png)

And this is also in GTK `gvim` using my preferred `darkburn` [colorscheme](https://github.com/nyvath/vim/blob/master/colors/darkburn.vim):

![2015-09-11-090929_1920x1080_scrot](https://cloud.githubusercontent.com/assets/1043958/9809050/2908ebf2-5865-11e5-8887-b4a5cef0648c.png)

Any chance to fix that? Unless these are my `vim` settings that are screwed up somehow...

**Comment by pearofducks** [comment]
Should be fixed, turns out *I'm* the one who only tested with weird colorschemes. Thanks for filing the issue!
