### ISSUE TITLE
Ability to goto role file

### ISSUE THREAD

**Issue by mtyurt** [pearofducks/ansible-vim#101]
I've implemented a custom mapping that behaves like `gf` but goes to the role under cursor's `tasks/main.yml` file. I'm not sure if it's beneficial for general use, but I can open a PR about it with following functionalities:

- *custom key mapping:* I'm using `<leader>gr` but it should be customizable
- *lookup paths:* default is `./roles`, should be comma-separated for multiple paths
- *default goto file:* default is `tasks/main.yml`

**Comment by pearofducks** [comment]
That's great! Thanks for reaching out to add it so other's can benefit.

Do you think it'd work to have these mappings linked to from the `README`? Either a gist or repo you can put up. Alternatively we could put them directly in the `README`, but I don't know that that's any more helpful.

I'd like to get these available for others to use, but not increase the maintenance surface of this plugin anymore - as I'm the only maintainer and have other projects as well.

**Comment by mtyurt** [comment]
Sure, that's understandable. Here is the [permalink to the script](https://github.com/mtyurt/dotfiles/blob/a25a44005d53426ec9409c335695c8aedd94cd92/vimrc#L551..L567). This is my first official custom function implementation, so there might be issues :) 

The alternatives are:
- reference above script from README (repo or commit might go away, though I'll try to keep it)
- export it to a gist and link to it (gist might go away :))
- paste the script into README directly (16 lines of code in vimrc is longer than I'd prefer)
- add it to the plugin code (would increase project maintenance)

WDYT?

**Comment by pearofducks** [comment]
I think a Gist makes sense, you'd have to explicitly take action on the Gist in order for it to go away.
