### ISSUE TITLE
Completion/autocompletion support

### ISSUE THREAD

**Issue by gardar** [pearofducks/ansible-vim#107]
Are there any plans/interest of adding completion/autocompletion of ansible module names, options and common args. or is would that be better served in a different plugin?

I'm imagining it could be done in a similar manner to the snips already included. 
I came a cross a atom plugin that could possibly be used as inspiration: https://github.com/h-hirokawa/atom-autocomplete-ansible

**Comment by pearofducks** [comment]
I have no plans of implementing this myself. I'm happy to accept a PR for it though - unless the code is quite complex to implement it ofc - then perhaps it should live in it's own plugin.

**Comment by gotmax23** [comment]
This would be especially helpful now that Ansible recommends using FQCNs.

**Comment by gardar** [comment]
Closing since I found the plugin [coc-ansible](https://github.com/yaegassy/coc-ansible) which does this (and more). Been using it for the past few months with great success.
