### ISSUE TITLE
Playbooks in playboosk directory nor recognized as ansible FileType

### ISSUE THREAD

**Issue by xenlo** [pearofducks/ansible-vim#112]
As far as I know, it's quite common to have all the playbooks files under a `playbooks` directory. So I propose to add that directory in the FileType detection.

**Comment by pearofducks** [comment]
We set the canonical directories to be detected already - other directories or filenames are trivial to set up for yourself in your `.vimrc`

**Comment by xenlo** [comment]
That's sad, but sounds fair with your explanation.

For documentation purpose, and to help anyone with same need who ends here, here is how I solved it in my vimrc: 
```vim
autocmd BufRead,BufNewFile */playbooks/** set filetype=yaml.ansible
```
