### ISSUE TITLE
generate.sh seems to require bash for no apparent reason.

### ISSUE THREAD

**Issue by Bubbelb** [pearofducks/ansible-vim#116]
Since I am trying Alpine to run Ansible and Neovim, the post install throws me an error.
Mind you that Alpine does not install bash by default, and I use zsh.

Upon investigation, it seems the first line is probelmatic:

``#!/usr/bin/env bash``

As the script is fairly simple, this line could be replaced by:

`` #!/bin/sh``

For the completeness, line 2 and 3 also seem redundant. (set, and IFS)

**Comment by pearofducks** [comment]
I don't think this is a worthwhile problem to solve.

I'd rather leave this as a bash script so anyone working on it in the future doesn't need to worry about whether something is a bash-ism or not.

I think it's fair to expect anyone working in the Ansible domain to have bash installed.

**Comment by Bubbelb** [comment]
Well, I don't agree, obviously.

It can be easily debuggged if something is bash-ism gets in the way in the script. The complexity of the script isn't that enourmous, that you can't simply find-and-fix bash-isms in minutes, if you happen to run into one.

Something that may be helpful: Why not execute the generate.py script directly, in stead of via a shell script? In the script you go a long way to figure out what python binary is used by Ansible. Since python2 is no more, there is only one. And, for that matter, generate.py explicitly uses python3 (as stated in line 1). So what is the point of figuring out what python version is used? E.G. what is the point of the shell script itself?

Maybe I'm just missing something here. I'm no python expert, but maybe it helps to improve ansible-vim.
