### ISSUE TITLE
Consider tagging a new git release

### ISSUE THREAD

**Issue by anthraxx** [pearofducks/ansible-vim#134]
Hi, first thank you for this vim script.

I'd like to ask if you could tag a new git tag? There hasn't been much movement since the last one, just 6 commits. But this doesn't seem to need that much active maintenance anyway and the last release is from 2021.

I'd be happy, as a new git tag means distros where this is available via the package manager can catch up those 6 adjustments :cat: 

Thank you!

**Comment by pearofducks** [comment]
Good call, thanks for the nudge. 

Done [here](https://github.com/pearofducks/ansible-vim/releases/tag/3.3)!
