### ISSUE TITLE
Should highlight with_file

### ISSUE THREAD

**Issue by kleinstuff** [pearofducks/ansible-vim#18]
I dont know if this is newer than your plugin, but, "with_file" is not highlighted.

**Comment by pearofducks** [comment]
Can't reproduce, and should be highlighted, all 'with_*' are selected:

https://github.com/pearofducks/ansible-vim/blob/master/syntax/ansible.vim#L89

**Comment by kleinstuff** [comment]
Hi, sorry, my bad. For some reason it was not highlighting, changed identation and it started to work fine.

**Comment by pearofducks** [comment]
No prob, glad it works!
