### ISSUE TITLE
Syntax highlighting of concatenated function arguments

### ISSUE THREAD

**Issue by habitullence** [pearofducks/ansible-vim#21]
https://gist.github.com/habitullence/bc10eff328345378448f671dc8cbaae2#file-main-yml-L35

After the single quotes on this line syntax highlighting breaks.

**Comment by pearofducks** [comment]
Thanks for reporting, unfortunately this is a bug in Vim's own YAML syntax - which this plugin uses to establish a (mostly) solid foundation. For now I'm just leaving the few bugs that exist alone, but am happy to accept PRs for them!

As a workaround, adding a space seems to make YAML happy - e.g. `( '* '`
