### ISSUE TITLE
Certain lines when replacing a character re-indent themselves (GIF example)

### ISSUE THREAD

**Issue by xenithorb** [pearofducks/ansible-vim#24]
I'm not sure how to describe this problem, so i made a GIF of the event. I find this extremely annoying because it happens seemingly randomly, and not always in this exact case. It's also dependent on `filetype plugin indent on` being set in `~/.vimrc`

![cloudyglisteningamericanquarterhorse-size_restricted](https://cloud.githubusercontent.com/assets/10273878/16884328/c31d903e-4a96-11e6-8924-1155c8611ea8.gif)

The problem also happens sometimes after entering a newline, which has the added annoyance of having to go up a line, then fix. The GIF example shows that you have to move back a word in order to remove the additional indent. 

I know in the GIF it looks like I have a very custom setup, but I did verify with a blank `.vimrc` + the bare minimum necessary to use this plugin through pathogen. 

Edit: it also happens only when this is present and loaded, not when using the default YAML definitions.

**Comment by pearofducks** [comment]
While this is expected behavior (it does help in certain indent-situations), you can disable it with:

`autocmd FileType ansible setlocal indentkeys-=<:>`

**Comment by xenithorb** [comment]
Ah, I see. I came across something very similar, here: https://stackoverflow.com/a/32420855

But it didn't work, I guess the key was setting it for the specific FileType. Likely I didn't realize that it needed to be `ansible` and that `yaml` would supersede that.

Thanks for the tip!
