### ISSUE TITLE
Subkeys don't highlight unless ownsyntax called

### ISSUE THREAD

**Issue by michaeldfallen** [pearofducks/ansible-vim#28]
Bit of a weird issue here.

When opening a file initially you see the following:
![image](https://cloud.githubusercontent.com/assets/1446145/20277977/d7cc0952-aa9a-11e6-8d08-162762a23992.png)

then when you run `:ownsyntax` you get:
![image](https://cloud.githubusercontent.com/assets/1446145/20278022/07d499d4-aa9b-11e6-9ea9-dcce0ccbcee7.png)

----------------------------------------------

Using the following snippet to inspect which rules are running

`:set statusline=%{synIDattr(synIDtrans(synID(line('.'),col('.'),1)),'name')}`

on the initial opening the highlighted key is a `Identifier` and the unhighlighted subkey is a `yamlPlainScalar`. After running `:ownsyntax` they are both `Identifier`.

**Comment by pearofducks** [comment]
Can't reproduce. Are you sure it's using the `ansible` filetype? What do you get for `echo &ft`.

**Comment by michaeldfallen** [comment]
`echo &ft` gives `ansible`. Probably something else I've installed is conflicting. I'll try installing a fresh Vim on a VM and see if I can find what plugin is conflicting.
