### ISSUE TITLE
Add ansible.cfg check to detection list

### ISSUE THREAD

**Issue by mblarsen** [pearofducks/ansible-vim#29]
For more complex setup you tend do break down playbooks inventories and roles into sub-dirs. It would be nice if a check for the existence of `ansible.cfg` file exists to the list of ft detection.

**Comment by pearofducks** [comment]
`ansible.cfg` uses the `cfg` filetype out of the box with Vim, which seems to provide sane highlights - thus I don't think replacing it is in the scope of this plugin.

If for some reason you do want one of the filetypes in this plugin to highlight `.cfg` then you can use [this](http://vim.wikia.com/wiki/Change_filetype_based_on_directory_path) method to select appropriate files and set filetypes.

**Comment by mblarsen** [comment]
I didn't mean for it to be highlighted by the plugin. But use the existence of it as a clue to when to set ft on YAML files. Just like the existence of `group_vars` does.

So if the current folder (or VCS root) has `ansible.cfg` then assume the file type of YAML types are ansible.

**Comment by pearofducks** [comment]
I understand now, sorry for the initial mixup.

However, this type of detection isn't really practical in Vim. A plugin like this gets the path to the file, so doing this detection would mean walking backwards in the tree looking for `ansible.cfg` - which could quickly get expensive.

It's a great suggestion, and if someone is able to implement this without drawbacks I'm happy to accept the PR!

**Comment by mblarsen** [comment]
Ah I see so the mention of `group_vars` refers to when it is included in the yaml files path right?

**Comment by pearofducks** [comment]
Correct :)
