### ISSUE TITLE
Support spell checking

### ISSUE THREAD

**Issue by nsg** [pearofducks/ansible-vim#31]
I'm not sure how easy this is to implement, and it's possible that I will look closer to this myself during the holidays but working spell checking would be really nice for me to have as a dyslexic non-English speaker :)

`example.yml` with `filetype=yaml`
![selection_023](https://cloud.githubusercontent.com/assets/16388/21354534/cb636aec-c6ca-11e6-9451-6851384d7dbf.png)

`example.yml` with `filetype=ansible`
![selection_024](https://cloud.githubusercontent.com/assets/16388/21354551/d7bef8c4-c6ca-11e6-930f-d5891af1788f.png)

I'm using the latest code from master, commit 8540ad7ff0f8da2b31b5c55e6ae52ad87221e918. Vim 7.4 (packaged by Ubuntu). I'm happy to help to fix this but not sure where to start, I'm mostly a vim user, not a hacker :)

**Comment by pearofducks** [comment]
I think at best the plugin could support checking comments. Checking anything else would be pretty noisy and a bad user experience, because quite a few 'words' in a playbook won't be _dictionary words_.
