### ISSUE TITLE
how to set the options

### ISSUE THREAD

**Issue by jasonwangnanjing** [pearofducks/ansible-vim#41]
Hi ,

Can u let  me know where i could set the variables like  g:ansible_unindent_after_newline = 1?

tks! in advance.

**Comment by pearofducks** [comment]
You set these in your `.vimrc` file.

My vimrc file is viewable [here](https://gist.github.com/pearofducks/68f1c481bac301875e62bee16a216e1d#file-vimrc-L48), and I've highlighted one of these config lines.
