### ISSUE TITLE
UltiSnips generation fails

### ISSUE THREAD

**Issue by chauncey-garrett** [pearofducks/ansible-vim#43]
I'm using `python2` and have `ansible` installed via `pip`. Installation fails with this error:

```
Traceback (most recent call last):
  File "./UltiSnips/generate.py", line 9, in <module>
    from ansible.utils.module_docs import get_docstring
ImportError: No module named module_docs
```
![image](https://user-images.githubusercontent.com/302358/30756381-1e94a444-9f90-11e7-9e9d-369dc52a8b52.png)

**Comment by pearofducks** [comment]
Regression against Ansible 2.4 - fixed now - thanks for reporting!
