### ISSUE TITLE
Variables in comments are still highlighted

### ISSUE THREAD

**Issue by redlegoman** [pearofducks/ansible-vim#47]
Not sure if it is my environment or not, but when I use ansible-vim and put a comment # at the beginning of a line containing a variable, the variable is still highlighted. So in

```
#- debug: msg="password for {{item.name}}"
```
![screenshot - 10_11_2017 11_40_19](https://user-images.githubusercontent.com/1895294/32657002-f3eab7d6-c60b-11e7-871b-f692c3dd0094.png)

the `{{item name}}` part of the line isn't the same colour as the rest of the line, which is in my case DarkBlue.

**Comment by pearofducks** [comment]
I can reproduce this, but it's a pretty rare corner-case - and doesn't break any other highlighting. I'm welcome to PRs that fix the issue, but won't spend time fixing it. :)

Thanks for reporting though!
