### ISSUE TITLE
weird playbook indenting issue

### ISSUE THREAD

**Issue by jdlovins** [pearofducks/ansible-vim#51]
Hey, 

I'm more or less new to ansible and im working on writing a playbook using the generic format as follows
```
.
├── roles
│   └── sshd
│       ├── defaults
│       │   └── main.yml
│       ├── files
│       │   └── laptop.pub
│       ├── handlers
│       │   └── main.yml
│       ├── meta
│       │   └── main.yml
│       ├── README.md
│       ├── tasks
│       │   └── main.yml
│       ├── templates
│       ├── tests
│       │   ├── inventory
│       │   └── test.yml
│       └── vars
│           └── main.yml
└── sshd.yml
```

While editing the sshd.yml file which is the main playbook and starting it off with
```
---
- name: configure sshd
```
then i want to add the hosts: setting, it unindents it once i type ':' which is super annoying. According to what i've found this is the right format so im not sure whats going on.

What I'm looking for
```
---
- name: sshd configs
  hosts: all
```

what im getting

```
---
- name: sshd configs
hosts: all
```

Thanks!

**Comment by pearofducks** [comment]
I can't reproduce this, and it doesn't sound like something this plugin causes.

Can you provide a reproduction through a `vimrc`?

What do you get when you do `echo &ft` as a command with this file open?

**Comment by jdlovins** [comment]
Hmm that's weird since this is a mostly bare bones centos 7 install. This is the only plugin i have installed besides Plug.
```
set nocp
call plug#begin('~/.vim/plugged')
	Plug 'pearofducks/ansible-vim'
	Plug 'stephpy/vim-yaml'
call plug#end()
filetype plugin indent on
syntax on
set encoding=utf-8
```
Is the vimrc file, i actually copied it from one of the other issues that i was poking around that.

Ah so ``echo &ft`` on that file shows yaml whereas doing it in tasks/main.yml shows ``ansible`` so its not registering the filetype properly. Which is weird since its in a folder that has ``roles`` as shown by the tree structure.

**Comment by jdlovins** [comment]
I'm sure theres a better way to do it but this is what i did with modifying your ftdetect part.
```
function! s:isAnsible()
  let filepath = expand("%:p")
  let filename = expand("%:t")
  let pwd = expand("%:h")

  if filepath =~ '\v/(tasks|roles|handlers)/.*\.ya?ml$' | return 1 | en
  if filepath =~ '\v/(group|host)_vars/' | return 1 | en
  if filename =~ '\v(playbook|site|main|local)\.ya?ml$' | return 1 | en

  let localfiles = split(globpath(pwd, '*'), '\n')

  for file in localfiles
        if file =~ '\v/(roles|group_vars|host_vars)$' | return 1 | en
  endfor

  let shebang = getline(1)
  if shebang =~# '^#!.*/bin/env\s\+ansible-playbook\>' | return 1 | en
  if shebang =~# '^#!.*/bin/ansible-playbook\>' | return 1 | en

  return 0
endfunction
```

**Comment by pearofducks** [comment]
In the top of the README there's a command you can put in your vimrc to let you set any regex to any filetype. That should support any use-cases you have.
