### ISSUE TITLE
incorrect syntax highlighting "{{ foo }}"."{{ bar }}"

### ISSUE THREAD

**Issue by philbert** [pearofducks/ansible-vim#6]
Seems that most characters in front of a ```"``` except for a space or another quote will break the syntax highlighting. 

You can check this task in a tasks/main.yml and the text afterward will have the wrong colours. 
```
  - name: break ansible-vim syntax highlighting
    shell: echo "{{ foo }}"."{{ bar }}"

  - name: this task will have colours as it in quotes
    shell: echo "Hello world"
```

I tried to fix it myself but there was too much of a learning curve

**Comment by pearofducks** [comment]
Hey, thanks for the bug report!

This is actually broken in YAML highlighting itself in vim, not ansible-vim. You can reproduce if you set the filetype to YAML, as seen [here](http://imgur.com/a/xi0v0).

I'll leave this open and try to take a look at upstream YAML to see if there's something easily patched.

**Comment by philbert** [comment]
Yeah vim's inbuilt yaml syntax highlighting is bad, hence why I use your plugin :)

Unfortunate to hear it's a vim issue. I've heard it can be frustrating getting vim pull requests merged (hence neovim).

**Comment by MJohnson459** [comment]
If anyone else finds this issue as a top search result for this bug, installing https://github.com/stephpy/vim-yaml fixes the issue.
