### ISSUE TITLE
YAML scalar after `when:` should always be jinja2 implicitly

### ISSUE THREAD

**Issue by towolf** [pearofducks/ansible-vim#60]
Is it possible to always highlight the value of a `when:` key as jinja? 

> ... the when clause, which contains a raw Jinja2 expression without double curly braces
— http://docs.ansible.com/ansible/latest/user_guide/playbooks_conditionals.html

**Comment by pearofducks** [comment]
Feel free to fork and add this yourself, I don't see this as a worthwhile feature to add.

It should be possible since the key can be detected.
