### ISSUE TITLE
Syntax incorreclty classifies Vim default fold markers.

### ISSUE THREAD

**Issue by cenouro** [pearofducks/ansible-vim#63]
I'm trying to use Vim fold markers (defaults are `{{{` and `}}}`, inside comments). On a normal `yaml` file, they are classified correctly as `yamlComment`; on a `yaml.ansible` file, they are classified as `jinjaVarDelim` and are highlighted incorrectly.

All my tests have been done using the following Vim command:
`:echo synIDattr(synID(line("."),col("."),1), "name")`

**Comment by pearofducks** [comment]
Feel free to submit a PR for this, otherwise this will be a pretty low-priority fix. This bug would have been around for a very long time now, and either it hasn't bothered anyone or you're the first to notice it! :)
