### ISSUE TITLE
Suggestion: Have a feature that allows you to open a role in another tab

### ISSUE THREAD

**Issue by lanceofwhichwedream** [pearofducks/ansible-vim#70]
It would be incredibly handy if this plugin allowed you to open a role that's defined in the playbook you are working in in another tab so that you don't lose your train of thought, for ease it could be that the plugin assumes the ansible directory is laid out according to the example layout listed in the ansible documentation

**Comment by pearofducks** [comment]
I agree this would be nice, but think this falls outside the scope of this plugin.

This plugin is focused on syntax highlight, and setting a few sensible Vim defaults.
