### ISSUE TITLE
Indent issue when typing ':' or '-'

### ISSUE THREAD

**Issue by sorsasampo** [pearofducks/ansible-vim#71]
Example file:

```yaml
---
- apt_repository:
    repo
```

If you type ':' or '-' in the end, it will get indented to:

```yaml
---
- apt_repository:
repo:
```

Minimal vimrc to reproduce:

```vim
set nocp
call plug#begin('~/.vim/plugged')
Plug 'pearofducks/ansible-vim'
call plug#end()
filetype plugin indent on
syntax on
set ai
set si
```

`set ft?` says `filetype=yaml.ansible`.

**Comment by pearofducks** [comment]
Can't reproduce vs vim 8.1 and that vimrc.

This is almost definitely not an issue in the plugin, as there's been no changes for several months and no one has reported indentation issues.

**Comment by sorsasampo** [comment]
My vim is from Debian stretch, version 2:8.0.0197-4+deb9u1.

What else could be causing this?

I have been trying to reproduce this easily for quite some time, but without success earlier. There seem to be a bit similar closed issues.

**Comment by pearofducks** [comment]
The closed issues are all false-positives. I'm not sure what could be causing this, but I'll leave this issue open for a bit and feel free to update if you find a root cause.

**Comment by sorsasampo** [comment]
This is still reproducing (at least some of the time), but I seriously have no idea what is causing it, and that's frustrating me a lot.

**Comment by pmyjavec** [comment]
Having this one too, hopefully I can find some time to debug it, disabling the plugin fixes it for now.
