### ISSUE TITLE
Plugin doesn't seem to recognize syntax

### ISSUE THREAD

**Issue by miguellavalle** [pearofducks/ansible-vim#75]
Hi,

This is a continuation to https://github.com/pearofducks/ansible-vim/issues/74. Trying to debug the issue, I added the following to my .vimrc:

map <F10> :echo "hi<" . synIDattr(synID(line("."),col("."),1),"name") . '> trans<'
\ . synIDattr(synID(line("."),col("."),0),"name") . "> lo<"
\ . synIDattr(synIDtrans(synID(line("."),col("."),1)),"name") . ">"<CR>

When editing this file https://github.com/miguellavalle/OpenStack-tools/blob/master/ansible/nova-net-migration/prep-compute-nodes-migration.yml, if I place the cursor on top of "name" in line 8, the echo I get is: 

hi<> trans<> lo<>

So it's not recognizing the syntax. The only thinks that seem to be recognized are attributes like "path" in line 9 (hi<ansible_attributes> trans<ansible_attributes> lo<GruvboxAqua> and jinja variables and delimiters, like in line 13 (hi<jinjaVariable> trans<jinjaVariable> lo<GruvboxPurple> and hi<jinjaVarDelim> trans<jinjaVarDelim> lo<GruvboxOrange>). Would this be attributable toi the plugin?

**Comment by pearofducks** [comment]
No, this still doesn't sound like a problem with this plugin.

What do you get if you do `echo &ft` with that file open?

**Comment by miguellavalle** [comment]
I get: ansible

**Comment by miguellavalle** [comment]
Thanks for your help and prompt follow up ;-)

**Comment by pearofducks** [comment]
Glad you were able to get things resolved!
