### ISSUE TITLE
Adopt a play/block/task approach in highlighting

### ISSUE THREAD

**Issue by tterranigma** [pearofducks/ansible-vim#76]
According to [this](https://docs.ansible.com/ansible/latest/reference_appendices/playbooks_keywords.html), there are three types of keywords, play-, block- and task-level keywords. It would be nice to have different highlighting for those three groups. 

There are also some keywords (like `run_once`) that are currently missing in general.

**Comment by pearofducks** [comment]
I don't agree with this.

First, distinguishing between a role/block/play `become` (or really any key) _sounds_ non-trivial. I'm not interested in further complicating the scope of this plugin.

Second, I don't agree that this brings extra value in highlighting - I'm not sure how it helps to have a block-keyword highlighted differently than a play-keyword - keywords are generally treated differently for what they _do_ not where they _are_.

---

I am, however, interested in keeping the highlighting coverage in line with Ansible current keywords - feel free to submit a PR for any of those!
