### ISSUE TITLE
UtilSnips Generat arguments

### ISSUE THREAD

**Issue by GaboFDC** [pearofducks/ansible-vim#83]
So I just started using this plugin, is really awesome, and thanks for it.
I noticed that the snippets where in multiline, so I went and check and saw that it is a parameter passed to `generate.py` but as it is wrapped in `generate.sh` it won't receive the parameter.
Also, this could be mentioned in the root readme so people is aware of this option

**Comment by pearofducks** [comment]
PR welcome to fix these issues, otherwise I'll take a look as soon as I can.

Thanks for the heads up on this regardless!
