### ISSUE TITLE
Issue generating snippets

### ISSUE THREAD

**Issue by myroslavrys** [pearofducks/ansible-vim#87]
**Environment**
macOS 10.15.2
NeoVim 
Python 3.7.6 (installed with Homebrew)

ansible 2.9.2 (installed with python pip)
  config file = None
  configured module search path = ['/Users/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/user/.homebrew/lib/python3.7/site-packages/ansible
  executable location = /Users/user/.homebrew/bin/ansible
  python version = 3.7.6 (default, Jan  2 2020, 02:05:27) [Clang 11.0.0 (clang-1100.0.33.16)]

NVIM v0.4.3
Build type: Release
LuaJIT 2.0.5
Compilation: /Users/user/.homebrew/Library/Homebrew/shims/mac/super/clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/tmp/neovim-20191127-79160-1ile155/neovim-0.4.3/build/config -I/tmp/neovim-20191127-79160-1ile155/neovim-0.4.3/src -I/Users/user/.homebrew/include -I/tmp/neovim-20191127-79160-1ile155/neovim-0.4.3/deps-build/include -I/Users/user/.homebrew/opt/gettext/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include -I/tmp/neovim-20191127-79160-1ile155/neovim-0.4.3/build/src/nvim/auto -I/tmp/neovim-20191127-79160-1ile155/neovim-0.4.3/build/include
Compiled by user@mbp.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/Users/user/.homebrew/Cellar/neovim/0.4.3/share/nvim"

**Error with snippet generation**
ansible-vim master ⦾ ./UltiSnips/generate.sh
[WARNING]: Failed to assign id for <_ast.Tuple object at 0x1023b2c10> on
/Users/user/.homebrew/lib/python3.7/site-
packages/ansible/modules/utilities/logic/async_wrapper.py, skipping

**Error in NeoVim**
An error occured. This is either a bug in UltiSnips or a bug in a
snippet definition. If you think this is a bug, please report it to
https://github.com/SirVer/ultisnips/issues/new
Please read and follow:
https://github.com/SirVer/ultisnips/blob/master/CONTRIBUTING.md#reproducing-bugs

Following is the full stack trace:
Traceback (most recent call last):
  File "/Users/user/.config/nvim/plugged/ultisnips/pythonx/UltiSnips/err_to_scratch_buffer.py", line 18, in wrapper
    return func(self, *args, **kwds)
  File "/Users/user/.config/nvim/plugged/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 198, in snippets_in_current_scope
    snippets = self._snips(before, True)
  File "/Users/user/.config/nvim/plugged/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 668, in _snips
    source.ensure(filetypes)
  File "/Users/user/.config/nvim/plugged/ultisnips/pythonx/UltiSnips/snippet/source/file/base.py", line 31, in ensure
    self._load_snippets_for(ft)
  File "/Users/user/.config/nvim/plugged/ultisnips/pythonx/UltiSnips/snippet/source/file/base.py", line 53, in _load_snippets_for
    self._parse_snippets(ft, fn)
  File "/Users/user/.config/nvim/plugged/ultisnips/pythonx/UltiSnips/snippet/source/file/base.py", line 70, in _parse_snippets
    raise SnippetSyntaxError(filename, line_index, msg)
UltiSnips.snippet.source.file.base.SnippetSyntaxError: Invalid multiword trigger: 'cp_mgmt_run_ips_update "Runs IPS database update. If "package-path' in ~/.config/nvim/plugged/ansible-vim/UltiSnips/ansible.snippets:27491

**Comment by pearofducks** [comment]
This is not an error, it's a warning, snippets seem to generate fine.
