### ISSUE TITLE
indent after hyphenated line

### ISSUE THREAD

**Issue by parmstro** [pearofducks/ansible-vim#9]
When editing a file and providing, as an example, a handler. The plugin returns the next line to the indent of the hyphen. It should return the position two spaces after the hyphen

Actual result:
<pre>
handlers:
          - name: Restart Apache
          service: name=httpd state=restarted
</pre>
ansible-playbook ....
ERROR: Syntax Error while loading YAML script, /home/ansible/sample.yaml
Note: The error may actually appear before this position: line 19, column 11
          - name: Restart Apache
          service: name=httpd state=restarted

Expected result:
<pre>
handlers:
          - name: Restart Apache
            service: name=httpd state=restarted
</pre>
ansible-playbook runs without error

**Comment by parmstro** [comment]
This condition should be picked up by:
<pre>
let s:array_entry = '\v^\s*-\s' " - foo
let s:named_module_entry = '\v^\s*-\s*(name|hosts):\s*\S' " - name: 'do stuff' 
...
if line =~ s:array_entry
    if line =~ s:named_module_entry
      return increase
...
</pre>

Hmmm... why not in my case...

**Comment by parmstro** [comment]
aahhhh... as soon as I add the : 
after the item in the next line like:
<pre>
handlers:
     - name: Restart Apache
       service
</pre>
it decreases the indent
<pre>
handlers:
     - name: Restart Apache
     service:
</pre>

**Comment by pearofducks** [comment]
The plugin is probably not causing this behavior (at least I can't reproduce it, and would expect someone else would have filed this issue before if it was happening), it's likely due to a setting in your `.vimrc` or the Ansible filetype not being loaded and Vim using YAML filetype instead.

You can see if the correct filetype is being used by doing `echo &syntax`

A good minimal `.vimrc` to test against is:

```
set nocp
call plug#begin('~/.vim/plugged')
Plug 'pearofducks/ansible-vim'
call plug#end()
filetype plugin indent on
syntax on
set encoding=utf-8
```

**Comment by parmstro** [comment]
Bingo...
yaml

On Sun, Mar 6, 2016 at 7:24 AM, Dave Honneffer <notifications@github.com>
wrote:

> The plugin is probably not causing this behavior (at least I can't
> reproduce it, and would expect someone else would have filed this issue
> before if it was happening), it's likely due to a setting in your .vimrc
> or the Ansible filetype not being loaded and Vim using YAML filetype
> instead.
>
> You can see if the correct filetype is being used by doing echo &syntax
>
> A good minimal .vimrc to test against is:
>
> set nocp
> call plug#begin('~/.vim/plugged')
> Plug 'pearofducks/ansible-vim'
> call plug#end()
> filetype plugin indent on
> syntax on
> set encoding=utf-8
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pearofducks/ansible-vim/issues/9#issuecomment-192882337>
> .
>



-- 
Paul Armstrong
Senior Solution Architect
Red Hat Canada
647-285-0044

**Comment by parmstro** [comment]
Also wasn't recognizing my filetype as ansible. Thanks I will track this
down.


On Sun, Mar 6, 2016 at 7:24 AM, Dave Honneffer <notifications@github.com>
wrote:

> The plugin is probably not causing this behavior (at least I can't
> reproduce it, and would expect someone else would have filed this issue
> before if it was happening), it's likely due to a setting in your .vimrc
> or the Ansible filetype not being loaded and Vim using YAML filetype
> instead.
>
> You can see if the correct filetype is being used by doing echo &syntax
>
> A good minimal .vimrc to test against is:
>
> set nocp
> call plug#begin('~/.vim/plugged')
> Plug 'pearofducks/ansible-vim'
> call plug#end()
> filetype plugin indent on
> syntax on
> set encoding=utf-8
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pearofducks/ansible-vim/issues/9#issuecomment-192882337>
> .
>



-- 
Paul Armstrong
Senior Solution Architect
Red Hat Canada
647-285-0044

**Comment by parmstro** [comment]
issue was file naming -> needed sample.yaml to be called
sample-playbook.yaml

:-( helps when I read the ftdetect file with any level of thoroughness...

Cheers,

Paul

On Sun, Mar 6, 2016 at 7:24 AM, Dave Honneffer <notifications@github.com>
wrote:

> The plugin is probably not causing this behavior (at least I can't
> reproduce it, and would expect someone else would have filed this issue
> before if it was happening), it's likely due to a setting in your .vimrc
> or the Ansible filetype not being loaded and Vim using YAML filetype
> instead.
>
> You can see if the correct filetype is being used by doing echo &syntax
>
> A good minimal .vimrc to test against is:
>
> set nocp
> call plug#begin('~/.vim/plugged')
> Plug 'pearofducks/ansible-vim'
> call plug#end()
> filetype plugin indent on
> syntax on
> set encoding=utf-8
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pearofducks/ansible-vim/issues/9#issuecomment-192882337>
> .
>



-- 
Paul Armstrong
Senior Solution Architect
Red Hat Canada
647-285-0044

**Comment by pearofducks** [comment]
Glad it's working now!
