### ISSUE TITLE
hilight issue when escaping quote in string

### ISSUE THREAD

**Issue by jcosmao** [pearofducks/ansible-vim#92]
Here is an example:

```
- set_fact:
    servers_filtered: "{{ servers.stdout | from_json | json_query(\"[?group_name=='\" + group_name + \"']\") }}"
```
jinja variable end }} is not detected correctly.

This line in jinja2.vim seems to be the issue:
```
34 " Jinja template constants
35  syn region jinjaString containedin=jinjaVarBlock,jinjaTagBlock,jinjaNested contained start=/"/ skip=/\(\\\)\@<!\(\(\\\\\)\@>\)*\\"/ end=/"/
```

**Comment by pearofducks** [comment]
Thanks for reporting! We only source Jinja (and include it here for convenience). Fixing bugs in their syntax is outside the scope of this project. You might wanna file this bug somewhere actively maintained like [here](https://github.com/Glench/Vim-Jinja2-Syntax/blob/master/syntax/jinja.vim).

If it does get resolved there, please let me know and I'll happily include their fix!
